# using categtrical navies bayes

In [1]:
import pandas as pd
import numpy as np

In [3]:
import pandas as pd

data = {
    "Outlook": [
        "Sunny", "Sunny", "Overcast", "Rain", "Rain", "Rain",
        "Overcast", "Sunny", "Sunny", "Rain", "Sunny", "Overcast",
        "Overcast", "Rain"
    ],
    
    "Temperature": [
        "Hot", "Hot", "Hot", "Mild", "Cool", "Cool",
        "Cool", "Mild", "Cool", "Mild", "Mild", "Mild",
        "Hot", "Mild"
    ],
    
    "Humidity": [
        "High", "High", "High", "High", "Normal", "Normal",
        "Normal", "High", "Normal", "Normal", "Normal", "High",
        "Normal", "High"
    ],
    
    "Wind": [
        "Weak", "Strong", "Weak", "Weak", "Weak", "Strong",
        "Strong", "Weak", "Weak", "Weak", "Strong", "Strong",
        "Weak", "Strong"
    ],
    
    "Play": [
        "No", "No", "Yes", "Yes", "Yes", "No",
        "Yes", "No", "Yes", "Yes", "Yes", "Yes",
        "Yes", "No"
    ]
}

df = pd.DataFrame(data)

df

,Outlook,Temperature,Humidity,Wind,Play
0,Sunny,Hot,High,Weak,No
1,Sunny,Hot,High,Strong,No
2,Overcast,Hot,High,Weak,Yes
3,Rain,Mild,High,Weak,Yes
4,Rain,Cool,Normal,Weak,Yes
5,Rain,Cool,Normal,Strong,No
6,Overcast,Cool,Normal,Strong,Yes
7,Sunny,Mild,High,Weak,No
8,Sunny,Cool,Normal,Weak,Yes
9,Rain,Mild,Normal,Weak,Yes


In [4]:
#seprating x and y
x=df.drop('Play',axis=1)
y=df['Play']

In [5]:
#train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [6]:
# data encoding
#target=lable encoding
#input = label encoding


In [7]:
# oridinal encoding
from sklearn.preprocessing import OrdinalEncoder
ordinal=OrdinalEncoder()
x_train_encode=ordinal.fit_transform(x_train)
x_test_encode=ordinal.transform(x_test)


In [8]:
# label encoding
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
y_train_ecode=label.fit_transform(y_train)
y_test_encode=label.transform(y_test)


In [9]:
#use categorical navies bayes algorithm as data is categoricsl
from sklearn.naive_bayes import CategoricalNB
model=CategoricalNB()
model.fit(x_train_encode,y_train_ecode)

,"alpha alpha: float, default=1.0Additive (Laplace/Lidstone) smoothing parameter(set alpha=0 and force_alpha=True, for no smoothing).",1.0
,"force_alpha force_alpha: bool, default=TrueIf False and alpha is less than 1e-10, it will set alpha to1e-10. If True, alpha will remain unchanged. This may causenumerical errors if alpha is too close to 0... versionadded:: 1.2.. versionchanged:: 1.4 The default value of `force_alpha` changed to `True`.",True
,"fit_prior fit_prior: bool, default=TrueWhether to learn class prior probabilities or not.If false, a uniform prior will be used.",True
,"class_prior class_prior: array-like of shape (n_classes,), default=NonePrior probabilities of the classes. If specified, the priors are notadjusted according to the data.",None
,"min_categories min_categories: int or array-like of shape (n_features,), default=NoneMinimum number of categories per feature.- integer: Sets the minimum number of categories per feature to `n_categories` for each features.- array-like: shape (n_features,) where `n_categories[i]` holds the minimum number of categories for the ith column of the input.- None (default): Determines the number of categories automatically from the training data... versionadded:: 0.24",None


In [10]:
y_pred=model.predict(x_test_encode)

In [11]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test_encode,y_pred)

0.3333333333333333

In [12]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_test_encode,y_pred)

array([[0, 1],
       [1, 1]])

In [13]:
print(classification_report(y_test_encode,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.50      0.50         2

    accuracy                           0.33         3
   macro avg       0.25      0.25      0.25         3
weighted avg       0.33      0.33      0.33         3



In [14]:
y_pred

array([1, 0, 1])

In [18]:
#bayes theorem#P(A∣B)=P(B∣A)P(A)
#        ---------
#         P(B)

#P(Play=Yes∣Outlook,Temperature,Humidity,Wind)
#P(Play=No∣Outlook,Temperature,Humidity,Wind)

In [20]:
#P(Play = No | features)
#P(Play = Yes | features)


label.classes_

array(['No', 'Yes'], dtype=object)

In [22]:

model.predict_proba(x_test_encode)
#here we got the probobitiy of tesing records only as our dataset was small of 14 rows from that 11 rows train and
#3 rows test henc only 3 records visible
# in each row we got the probability of both classes 0 and 1 for each testing record
#cosider row 1: no:0.22 < yes:0.77 so the model predicted yes for that record and similarly for other records

array([[0.22573363, 0.77426637],
       [0.53835801, 0.46164199],
       [0.43739748, 0.56260252]])

In [23]:
y_test_encode

array([1, 1, 0])

In [25]:
y_pred

array([1, 0, 1])

In [29]:
comparison = pd.DataFrame({
    "Actual": y_test_encode,
    "Predicted": y_pred
})

comparison["Result"] = comparison["Actual"]== comparison["Predicted"]

comparison

,Actual,Predicted,Result
0,1,1,True
1,1,0,False
2,0,1,False


In [30]:
comparison["Result"] = np.where(
    comparison["Actual"] == comparison["Predicted"],
    "Correct",
    "Wrong"
)

comparison

,Actual,Predicted,Result
0,1,1,Correct
1,1,0,Wrong
2,0,1,Wrong
